name: CI Cache Test

on:
  push:
    branches: [ main ]
  workflow_dispatch: # allow manual triggering

jobs:
  test-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: prime-cache-55de323
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
          key: cache-55de323

      - name: Show cache result
        run: echo "Cache result: ${{ steps.cache.outputs.cache-hit }}"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run example tests
        run: |
          echo "✅ Tests completed!"
